version: '3.8'
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easyrh-next
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
